<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="YSOD.aspx.cs" Inherits="demomvp.YSOD" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <br />
       <h2>Yellow Screen of Death</h2>
    
    <br />
    <asp:Label ID="message" runat="server"></asp:Label>
</asp:Content>
